version: 0.2

phases:
  install:
    commands:
      # Update libs
      - apt-get update
      # Headless Chrome
      - apt-get install nginx
      - apt-get install supervisor
      - apt-get install python-pip
      - apt-get install python-virtualenv
      - pip install gunicorn
  build:
    commands:
      - ./manage.py test
