version: 0.2

phases:
  install:
    commands:
      # Update libs
      - apt-get update
      # Headless Chrome
      - apt-get install nginx -y
      - apt-get install supervisor -y
      - apt-get install python-pip -y
      - apt-get install python-virtualenv -y
      - pip install gunicorn
  build:
    commands:
      - ./manage.py test
